# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e50847f065aebfb7ce8edb538d7925c052d425c86df820090e9de52fd4e3f024891248f7f526a0a2e4ae2fd105725f75899aad18055f047c02eebdc64238248

test:
  secret_key_base: 3e30c7200e1d93c836081834f1f4e7d920098141274dbf3da6d627e3d46df59479b7196d78910bf0506350e6203915005673081c5f387d7e8b5e2d8a8f161d2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
